sserver:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # create, create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      platform: mysql
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: quocltse161868@fpt.edu.vn
    password: frye vznr mwen gxso
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: c42478bdb24931ecb1ee79711b5c84db06917c3d472e3fcf64e48fb5e50c67a312e15d91eb08b9c78b46f4037fbd4db846c5038ac2ab5646913ab11fd23f35f0
  expiration: 31536000 # 1 year in milliseconds

google:
  api:
    key: your_google_api_key
